import type { NextPage } from 'next'
import Head from 'next/head'

import { Navbar, RoomInfo, SideContent } from '../components/collaborations'
import Editor from '../components/editor'
import Runner from '../components/runner'
import Result from '../components/result'

import { useStateContext } from '../contexts/ContextProvider'

const Home: NextPage = () => {
  const { collabStates }:any = useStateContext()

  const { colHide } = collabStates

  return (
    <div>
      <Head>
        <title>Collaborations </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col lg:flex-row w-full h-screen bg-[#4B5563] items-center lg:items-start justify-start">
        <Navbar />
        <SideContent />
        <div className={`flex flex-col ${colHide ? 'w-full lg:w-1/2 h-0 lg:h-full' : 'w-full h-full'} overflow-auto transition-all ease-in-out duration-500`}>
          <div className="flex flex-col w-full items-start justify-start py-2 px-2 gap-6">
            <RoomInfo />
            <Editor />
            <Runner />
            <Result />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
